#!/bin/bash

set -e

APP=gaslight
DB=${DB-gaslight_development}

dropdb --if-exists $DB
createdb $DB

heroku pgbackups:capture --expire --app $APP
curl -Lo latest.dump `heroku pgbackups:url --app $APP`
pg_restore --verbose --no-acl --no-owner -d $DB latest.dump

